[pytest]
pythonpath = src scripts ..
testpaths = tests
addopts = -q
filterwarnings =
    ignore:.*HTTP_422_UNPROCESSABLE_ENTITY.*:DeprecationWarning
    ignore:.*Using `httpx` with `starlette.testclient` is deprecated.*:Warning
